version: 0.2

phases:
  install:
    commands:
      - echo Installing Amazon EFS Utils...
      - sudo yum -y install amazon-efs-utils
  build:
    commands:
      - echo Mounting EFS...
      - mkdir ~/efs
      - echo "eu-central-1" > /tmp/aws-region
      - sudo mount -t efs -o tls,iam,region=$(cat /tmp/aws-region) fs-12345678:/ ~/efs  # replace with your EFS File System ID
  post_build:
    commands:
      - echo Copying files to EFS...
      - cp -R ./* ~/efs/
